# Generated by Django 4.1.13 on 2026-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
